# config.yaml
# Workbench设置
wbpj_template: "bridge_fsi_template.wbpj"
working_dir: "fsi_simulations"

# 随机变量参数
random_vars:
  V_b_100: 28.5  # 基本风速 (m/s)
  beta_coeff: 0.12  # Gumbel分布系数

# 优化参数
nsga_pop: 80
nsga_gen: 60

# 收敛参数
convergence:
  max_iter: 15
  tol: 0.01
  beta_tol: 0.005

# 损伤阈值
thresholds:
  Flutter_DS4: ["Ucr", 0.0]
  Displacement_DS1: ["sigma_q", 0.1]
  Displacement_DS2: ["sigma_q", 0.2]
  Displacement_DS3: ["sigma_q", 0.3]
  Acceleration_DS1: ["sigma_a", 0.05]
  Acceleration_DS2: ["sigma_a", 0.1]
  Acceleration_DS3: ["sigma_a", 0.15]

# FSI仿真开关
use_fsi: true